require("dotenv").config();
const { createRecipe } = require("./queries");
const pool = require("./pool");

const recipes = [
    {
        recipe_title: "Tuna Pasta Bake",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 30,
        ingredient_name: [
            "pasta",
            "tuna",
            "cream of tomato soup",
            "cheddar cheese",
        ],
        ingredient_quantity: [400, 2, 1, 100],
        ingredient_unit: ["g", "", "can", "g"],
        tags: [],
    },
    {
        recipe_title: "Chilli Con Carne",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 40,
        ingredient_name: [
            "beef mince",
            "kidney beans",
            "chopped tomatoes",
            "onion",
            "chilli powder",
        ],
        ingredient_quantity: [500, 1, 1, 1, 1],
        ingredient_unit: ["g", "can", "can", "medium", "tsp"],
        tags: [],
    },
    {
        recipe_title: "Tacos",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 20,
        ingredient_name: ["beef mince", "taco shells", "taco seasoning"],
        ingredient_quantity: [500, 12, 1],
        ingredient_unit: ["g", "", "sachet"],
        tags: [],
    },
    {
        recipe_title: "Spaghetti Bolognese",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 40,
        ingredient_name: [
            "spaghetti",
            "beef mince",
            "chopped tomatoes",
            "onion",
        ],
        ingredient_quantity: [400, 500, 1, 1],
        ingredient_unit: ["g", "g", "can", "medium"],
        tags: [],
    },
    {
        recipe_title: "Lasagne",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 20,
        cook_time_minutes: 50,
        ingredient_name: [
            "lasagne sheets",
            "beef mince",
            "chopped tomatoes",
            "onion",
            "béchamel sauce",
            "cheddar cheese",
        ],
        ingredient_quantity: [250, 500, 1, 1, 500, 100],
        ingredient_unit: ["g", "g", "can", "medium", "g", "g"],
        tags: [],
    },
    {
        recipe_title: "Chicken Fajitas",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 20,
        ingredient_name: [
            "chicken breast",
            "fajita seasoning",
            "flour tortillas",
            "red pepper",
            "onion",
        ],
        ingredient_quantity: [600, 1, 8, 1, 1],
        ingredient_unit: ["g", "sachet", "", "large", "large"],
        tags: [],
    },
    {
        recipe_title: "Prawn Fajitas",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 15,
        ingredient_name: [
            "raw king prawns",
            "fajita seasoning",
            "flour tortillas",
            "red pepper",
            "onion",
        ],
        ingredient_quantity: [400, 1, 8, 1, 1],
        ingredient_unit: ["g", "sachet", "", "large", "large"],
        tags: [],
    },
    {
        recipe_title: "Jacket Potatoes",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 5,
        cook_time_minutes: 60,
        ingredient_name: ["jacket potato", "butter"],
        ingredient_quantity: [4, 50],
        ingredient_unit: ["", "g"],
        tags: [],
    },
    {
        recipe_title: "Pizza Oven Pizza",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 10,
        ingredient_name: ["shop-bought pizza dough", "passata", "mozzarella"],
        ingredient_quantity: [4, 200, 250],
        ingredient_unit: ["", "ml", "g"],
        tags: [],
    },
    {
        recipe_title: "Chicken Kievs",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 5,
        cook_time_minutes: 35,
        ingredient_name: ["chicken kievs"],
        ingredient_quantity: [4],
        ingredient_unit: [""],
        tags: [],
    },
    {
        recipe_title: "Spare Ribs",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 120,
        ingredient_name: ["pork spare ribs", "BBQ sauce"],
        ingredient_quantity: [1500, 200],
        ingredient_unit: ["g", "ml"],
        tags: [],
    },
    {
        recipe_title: "Spatchcock Chicken with Beans and Couscous",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 60,
        ingredient_name: ["whole chicken", "couscous", "mixed beans"],
        ingredient_quantity: [1, 300, 1],
        ingredient_unit: ["", "g", "can"],
        tags: [],
    },
    {
        recipe_title: "Chicken Caesar Salad",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 15,
        ingredient_name: [
            "chicken breast",
            "romaine lettuce",
            "parmesan",
            "croutons",
            "Caesar dressing",
        ],
        ingredient_quantity: [600, 1, 50, 100, 100],
        ingredient_unit: ["g", "large", "g", "g", "ml"],
        tags: [],
    },
    {
        recipe_title: "Chickpea and Squash Pilaf",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url:
            "https://realfood.tesco.com/recipes/roasted-squash-and-chickpea-pilaf.html",
        prep_time_minutes: 15,
        cook_time_minutes: 40,
        ingredient_name: [
            "butternut squash",
            "chickpeas",
            "basmati rice",
            "onion",
        ],
        ingredient_quantity: [1, 1, 300, 1],
        ingredient_unit: ["medium", "can", "g", "medium"],
        tags: [],
    },
    {
        recipe_title: "Cheeseburger and Chips",
        recipe_description: "Served with rosemary crushed salted chips.",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 30,
        ingredient_name: [
            "beef mince",
            "burger buns",
            "cheddar cheese",
            "frozen chips",
        ],
        ingredient_quantity: [500, 4, 4, 800],
        ingredient_unit: ["g", "", "slices", "g"],
        tags: [],
    },
    {
        recipe_title:
            "Creamy Sausage and Courgette Pasta with Lemon and Pine Nuts",
        recipe_description:
            "Creamy sausage pasta with lemon-seasoned courgette and toasted pine nuts.",
        recipe_instructions:
            "1. Cook pasta in salted water until al dente. Reserve a little pasta water.\n2. In a large pan, fry courgette slices in olive oil until golden. Remove and set aside.\n3. In the same pan, sauté garlic with a pinch of salt, pepper, and lemon zest.\n4. Add sausage meat, cooking until browned and cooked through.\n5. Return courgettes to the pan. Stir in lemon juice, parmesan, basil, and cream cheese. Add a splash of pasta water if needed for creaminess.\n6. Toss the cooked pasta through the sauce.\n7. Serve topped with toasted pine nuts and extra parmesan.",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 25,
        ingredient_name: [
            "pasta",
            "courgette",
            "olive oil",
            "garlic cloves",
            "lemon",
            "sausage meat",
            "parmesan",
            "cream cheese",
            "fresh basil leaves",
            "pine nuts",
            "salt and black pepper",
        ],
        ingredient_quantity: [400, 1, 2, 3, 1, 275, 1, 1.5, 1, 1, 0],
        ingredient_unit: [
            "g",
            "",
            "tbsp",
            "cloves",
            "",
            "g",
            "handful",
            "tbsp",
            "handful",
            "handful",
            "",
        ],
        tags: [],
    },
    {
        recipe_title: "Turkey Meatballs / Burgers",
        recipe_description: "Good for snacks.",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 20,
        ingredient_name: ["turkey mince", "breadcrumbs", "egg"],
        ingredient_quantity: [500, 50, 1],
        ingredient_unit: ["g", "g", "large"],
        tags: [],
    },
    {
        recipe_title: "Fish Pie",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 20,
        cook_time_minutes: 45,
        ingredient_name: ["fish pie mix", "mashed potato", "milk", "butter"],
        ingredient_quantity: [600, 800, 200, 50],
        ingredient_unit: ["g", "g", "ml", "g"],
        tags: [],
    },
    {
        recipe_title: "Chicken Pie",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 20,
        cook_time_minutes: 45,
        ingredient_name: [
            "chicken breast",
            "shortcrust pastry",
            "chicken stock",
        ],
        ingredient_quantity: [600, 500, 300],
        ingredient_unit: ["g", "g", "ml"],
        tags: [],
    },
    {
        recipe_title: "Lentil Dhal",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 30,
        ingredient_name: [
            "red lentils",
            "onion",
            "chopped tomatoes",
            "coconut milk",
        ],
        ingredient_quantity: [300, 1, 1, 400],
        ingredient_unit: ["g", "medium", "can", "ml"],
        tags: [],
    },
    {
        recipe_title: "Sausage Carbonara",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 25,
        ingredient_name: [
            "pasta",
            "sausages",
            "eggs",
            "parmesan",
            "black pepper",
        ],
        ingredient_quantity: [400, 6, 3, 80, 1],
        ingredient_unit: ["g", "", "large", "g", "tsp"],
        tags: [],
    },
    {
        recipe_title: "Spanish Pork Belly",
        recipe_description: "Gusto recipe.",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 90,
        ingredient_name: [
            "pork belly",
            "smoked paprika",
            "garlic cloves",
            "olive oil",
        ],
        ingredient_quantity: [1000, 2, 4, 2],
        ingredient_unit: ["g", "tsp", "cloves", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Pork Belly Noodle Soup",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 60,
        ingredient_name: [
            "pork belly",
            "noodles",
            "chicken stock",
            "soy sauce",
        ],
        ingredient_quantity: [600, 300, 1000, 3],
        ingredient_unit: ["g", "g", "ml", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Steak and Chips",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 5,
        cook_time_minutes: 25,
        ingredient_name: ["sirloin steak", "frozen chips", "butter"],
        ingredient_quantity: [4, 800, 30],
        ingredient_unit: ["", "g", "g"],
        tags: [],
    },
    {
        recipe_title: "Prawn Paella",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url:
            "https://www.goodhousekeeping.com/uk/food/recipes/a570581/cheats-paella/",
        prep_time_minutes: 10,
        cook_time_minutes: 35,
        ingredient_name: [
            "raw king prawns",
            "paella rice",
            "chicken stock",
            "onion",
            "saffron",
        ],
        ingredient_quantity: [400, 300, 800, 1, 1],
        ingredient_unit: ["g", "g", "ml", "medium", "pinch"],
        tags: [],
    },
    {
        recipe_title: "Lamb Biryani",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "https://www.bbcgoodfood.com/recipes/lamb-biryani",
        prep_time_minutes: 20,
        cook_time_minutes: 90,
        ingredient_name: [
            "lamb shoulder",
            "basmati rice",
            "onion",
            "biryani spice mix",
        ],
        ingredient_quantity: [800, 400, 1, 2],
        ingredient_unit: ["g", "g", "large", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Chicken Gyros",
        recipe_description: "Air fryer chicken gyros.",
        recipe_instructions: "",
        recipe_link_url: "https://tasty.co/recipe/chicken-gyros",
        prep_time_minutes: 15,
        cook_time_minutes: 20,
        ingredient_name: [
            "chicken thighs",
            "pitta bread",
            "Greek yoghurt",
            "tzatziki",
            "lemon",
        ],
        ingredient_quantity: [600, 4, 200, 200, 1],
        ingredient_unit: ["g", "", "g", "g", ""],
        tags: [],
    },
    {
        recipe_title: "Lamb Stew",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 90,
        ingredient_name: [
            "lamb shoulder",
            "onion",
            "carrots",
            "potatoes",
            "lamb stock",
        ],
        ingredient_quantity: [800, 1, 3, 4, 500],
        ingredient_unit: ["g", "large", "medium", "medium", "ml"],
        tags: [],
    },
    {
        recipe_title: "Asparagus Carbonara",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url:
            "https://www.jamieoliver.com/recipes/pasta-recipes/5-ingredient-asparagus-carbonara/",
        prep_time_minutes: 10,
        cook_time_minutes: 20,
        ingredient_name: ["pasta", "asparagus", "eggs", "parmesan", "pancetta"],
        ingredient_quantity: [400, 250, 3, 80, 150],
        ingredient_unit: ["g", "g", "large", "g", "g"],
        tags: [],
    },
    {
        recipe_title: "Beef Meatballs with Turkish Rice, Wraps and Salad",
        recipe_description:
            "Meatballs rolled in chilli flakes, dried coriander, cumin, salt and pepper with garlic tucked inside. Served with vermicelli rice, wraps and houmous.",
        recipe_instructions:
            "Roll meatballs in chilli flakes, dried coriander, cumin, salt and pepper. Cut garlic chunks and stick in each meatball. Cook rice with vermicelli noodles. Serve with wraps, salad and houmous on the side.",
        recipe_link_url: "",
        prep_time_minutes: 20,
        cook_time_minutes: 25,
        ingredient_name: [
            "beef mince",
            "garlic cloves",
            "chilli flakes",
            "dried coriander",
            "cumin",
            "basmati rice",
            "vermicelli noodles",
            "flour tortillas",
            "houmous",
        ],
        ingredient_quantity: [500, 4, 1, 1, 1, 300, 50, 6, 200],
        ingredient_unit: [
            "g",
            "cloves",
            "tsp",
            "tsp",
            "tsp",
            "g",
            "g",
            "",
            "g",
        ],
        tags: [],
    },
    {
        recipe_title: "Boursin Cheese Chicken Pasta",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 25,
        ingredient_name: ["chicken breast", "pasta", "Boursin cheese"],
        ingredient_quantity: [600, 400, 150],
        ingredient_unit: ["g", "g", "g"],
        tags: [],
    },
    {
        recipe_title: "Wagamama Yaki Soba with Shrimp and Chicken",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 15,
        ingredient_name: [
            "soba noodles",
            "chicken breast",
            "raw king prawns",
            "yaki soba sauce",
        ],
        ingredient_quantity: [300, 400, 200, 100],
        ingredient_unit: ["g", "g", "g", "ml"],
        tags: [],
    },
    {
        recipe_title: "Shakshuka",
        recipe_description: "",
        recipe_instructions:
            "1. Heat olive oil in a large sauté pan over medium heat. Add diced onion and bell pepper. Cook for about 5 minutes until the onion becomes translucent. Add minced garlic, paprika, cumin, and chili powder. Stir for another minute until fragrant.\n2. Pour in the can of whole peeled tomatoes. Use a spatula to break the tomatoes into smaller pieces. Let the mixture simmer on low heat for about 10-15 minutes until it thickens slightly.\n3. Make small indentations in the tomato mixture for each egg. Crack an egg into each indentation. Reduce the heat to low and cook for 5-8 minutes, or until the eggs reach your preferred doneness.\n4. Season with salt and pepper. Garnish with freshly chopped parsley and cilantro. Serve directly from the pan with crusty bread or pita.",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 25,
        ingredient_name: [
            "onion",
            "red bell pepper",
            "garlic cloves",
            "whole peeled tomatoes",
            "paprika",
            "cumin",
            "chilli powder",
            "eggs",
            "fresh parsley",
            "fresh cilantro",
            "olive oil",
            "salt and pepper",
        ],
        ingredient_quantity: [1, 1, 3, 800, 1, 1, 0.25, 6, 1, 1, 2, 0],
        ingredient_unit: [
            "medium",
            "medium",
            "cloves",
            "g",
            "tsp",
            "tsp",
            "tsp",
            "large",
            "handful",
            "handful",
            "tbsp",
            "",
        ],
        tags: [],
    },
    {
        recipe_title:
            "Tandoori Lamb Chops with Bombay Potatoes, Mint Raita, Wraps and Rice",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "https://www.krumpli.co.uk/tandoori-lamb-chops/",
        prep_time_minutes: 20,
        cook_time_minutes: 30,
        ingredient_name: [
            "lamb chops",
            "tandoori marinade",
            "potatoes",
            "mint raita",
            "basmati rice",
            "flour tortillas",
        ],
        ingredient_quantity: [8, 150, 600, 200, 300, 6],
        ingredient_unit: ["", "g", "g", "g", "g", ""],
        tags: [],
    },
    {
        recipe_title: "Slow Cooked Beef Brisket in Red Wine",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url:
            "https://tastesofthyme.com/2023/02/02/the-best-red-wine-braised-shredded-beef-brisket/",
        prep_time_minutes: 20,
        cook_time_minutes: 240,
        ingredient_name: [
            "beef brisket",
            "red wine",
            "beef stock",
            "onion",
            "garlic cloves",
        ],
        ingredient_quantity: [1500, 300, 400, 1, 4],
        ingredient_unit: ["g", "ml", "ml", "large", "cloves"],
        tags: [],
    },
    {
        recipe_title: "Singapore Noodles",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 15,
        ingredient_name: [
            "rice vermicelli noodles",
            "raw king prawns",
            "char siu pork",
            "eggs",
            "curry powder",
            "soy sauce",
        ],
        ingredient_quantity: [200, 200, 150, 2, 2, 2],
        ingredient_unit: ["g", "g", "g", "large", "tsp", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Salmon Noodle Stir Fry",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 15,
        ingredient_name: ["salmon fillets", "noodles", "soy sauce"],
        ingredient_quantity: [4, 300, 3],
        ingredient_unit: ["", "g", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Homemade Breaded Cod Fish Fingers",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 20,
        ingredient_name: ["cod fillets", "breadcrumbs", "eggs", "plain flour"],
        ingredient_quantity: [600, 150, 2, 80],
        ingredient_unit: ["g", "g", "large", "g"],
        tags: [],
    },
    {
        recipe_title: "Thai Style Steamed Fish",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url:
            "https://www.bbcgoodfood.com/recipes/thai-style-steamed-fish",
        prep_time_minutes: 10,
        cook_time_minutes: 20,
        ingredient_name: [
            "white fish fillets",
            "ginger",
            "lemongrass",
            "soy sauce",
            "lime",
        ],
        ingredient_quantity: [4, 30, 1, 3, 1],
        ingredient_unit: ["", "g", "stalk", "tbsp", ""],
        tags: [],
    },
    {
        recipe_title: "BBQ Cheeseburger with Streaky Bacon",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 15,
        ingredient_name: [
            "beef mince",
            "burger buns",
            "cheddar cheese",
            "streaky bacon",
        ],
        ingredient_quantity: [500, 4, 4, 8],
        ingredient_unit: ["g", "", "slices", "rashers"],
        tags: [],
    },
    {
        recipe_title: "Lamb Kofte",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 15,
        ingredient_name: ["lamb mince", "onion", "cumin", "fresh parsley"],
        ingredient_quantity: [500, 1, 1, 1],
        ingredient_unit: ["g", "medium", "tsp", "handful"],
        tags: [],
    },
    {
        recipe_title: "Jerk Chicken",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 30,
        ingredient_name: ["chicken thighs", "jerk seasoning"],
        ingredient_quantity: [8, 3],
        ingredient_unit: ["", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Pork Souvlaki",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url:
            "https://www.bbc.co.uk/food/recipes/pork_souvlaki_with_58334",
        prep_time_minutes: 20,
        cook_time_minutes: 15,
        ingredient_name: [
            "pork shoulder",
            "lemon",
            "olive oil",
            "dried oregano",
            "pitta bread",
        ],
        ingredient_quantity: [700, 1, 3, 2, 4],
        ingredient_unit: ["g", "", "tbsp", "tsp", ""],
        tags: [],
    },
    {
        recipe_title: "Pizza - Salami, Mozzarella, Olives and Capers",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 12,
        ingredient_name: [
            "shop-bought pizza dough",
            "passata",
            "mozzarella",
            "salami",
            "olives",
            "capers",
        ],
        ingredient_quantity: [1, 150, 125, 80, 50, 2],
        ingredient_unit: ["", "ml", "g", "g", "g", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Pizza - Anchovies and Capers",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 15,
        cook_time_minutes: 12,
        ingredient_name: [
            "shop-bought pizza dough",
            "passata",
            "mozzarella",
            "anchovies",
            "capers",
        ],
        ingredient_quantity: [1, 150, 125, 50, 2],
        ingredient_unit: ["", "ml", "g", "g", "tbsp"],
        tags: [],
    },
    {
        recipe_title: "Chicken Pasta Soup",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 30,
        ingredient_name: [
            "chicken breast",
            "small pasta",
            "chicken stock",
            "onion",
            "carrots",
        ],
        ingredient_quantity: [400, 150, 1000, 1, 2],
        ingredient_unit: ["g", "g", "ml", "medium", "medium"],
        tags: [],
    },
    {
        recipe_title: "Chicken Pasta with Sweetcorn, Pepper and Onion",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 25,
        ingredient_name: [
            "chicken breast",
            "pasta",
            "sweetcorn",
            "red pepper",
            "onion",
        ],
        ingredient_quantity: [600, 400, 1, 1, 1],
        ingredient_unit: ["g", "g", "can", "large", "medium"],
        tags: [],
    },
    {
        recipe_title: "Grilled Butterfly Chicken Breast",
        recipe_description: "Served as a wrap, with rice, or with pasta.",
        recipe_instructions: "",
        recipe_link_url: "",
        prep_time_minutes: 10,
        cook_time_minutes: 15,
        ingredient_name: ["chicken breast", "olive oil", "salt and pepper"],
        ingredient_quantity: [4, 2, 0],
        ingredient_unit: ["large", "tbsp", ""],
        tags: [],
    },
    {
        recipe_title: "Make-Ahead Grain Bowls",
        recipe_description: "",
        recipe_instructions: "",
        recipe_link_url:
            "https://www.bbc.co.uk/food/recipes/make-ahead_grain_bowls_02072",
        prep_time_minutes: 15,
        cook_time_minutes: 30,
        ingredient_name: ["mixed grains", "roasted vegetables", "olive oil"],
        ingredient_quantity: [400, 500, 3],
        ingredient_unit: ["g", "g", "tbsp"],
        tags: [],
    },
];

async function seed() {
    try {
        for (const recipe of recipes) {
            await createRecipe(recipe);
            console.log(`Seeded: ${recipe.recipe_title}`);
        }
        console.log("Seeding complete.");
    } catch (error) {
        console.error("Seeding failed:", error);
    } finally {
        await pool.end();
    }
}

seed();
